### ISSUE TITLE
transfer ownership to nrdxp

### ISSUE THREAD

**Issue by colemickens** [nrdxp/cfdyndns#16]
Hi, @nrdxp,

GitHub is being picky.

`nrdxp already has a repository in the colemickens/cfdyndns network`

Want to delete your fork and I'll do the transfer again?

**Comment by nrdxp** [comment]
alright, it's gone :+1:

**Comment by colemickens** [comment]
and there we go. :pray:

**Comment by nrdxp** [comment]
Thanks you! Would you still like to be a maintainer?

**Comment by colemickens** [comment]
Sure!
