### ISSUE TITLE
NixOS failed to parse header value

### ISSUE THREAD

**Issue by JRodez** [nrdxp/cfdyndns#52]
Hi, it seems like something is broken... I'm using NIXOS 23.05 with 23.11 channel

> warning: the following units failed: cfdyndns.service
> 
> × cfdyndns.service - CloudFlare Dynamic DNS Client
>      Loaded: loaded (/etc/systemd/system/cfdyndns.service; enabled; preset: enabled)
>      Active: failed (Result: exit-code) since Tue 2024-01-16 17:01:39 CET; 1s ago
>    Duration: 452ms
> TriggeredBy: ● cfdyndns.timer
>     Process: 13145 ExecStart=/nix/store/7pdq2618p2fh703z3wz8ib30mbl2kiyq-unit-script-cfdyndns-start/bin/cfdyndns-start (code=exited, status=1/FAILURE)
>    Main PID: 13145 (code=exited, status=1/FAILURE)
>          IP: 562B in, 452B out
>         CPU: 118ms
> 
> janv. 16 17:01:38 jerserv systemd[1]: Started CloudFlare Dynamic DNS Client.
> janv. 16 17:01:38 jerserv cfdyndns-start[13163]:  INFO  cfdyndns::ip > 82.66.158.3
> janv. 16 17:01:38 jerserv cfdyndns-start[13163]:  INFO  cfdyndns::ip > 2a01:e0a:1b2:cd70:f3de:71ed:f9eb:6403
> janv. 16 17:01:39 jerserv cfdyndns-start[13163]: Error: builder error: failed to parse header value

**Comment by Pablo1107** [comment]
This a problem with how you set the environment file. The file should only contain the token, not a variable like `TOKEN=<token>`, just `<token>`.

**Comment by JRodez** [comment]
Thanks, but I have a static IP now, so I no longer need it.
