### ISSUE TITLE
Wrong Cargo.lock in v0.0.2

### ISSUE THREAD

**Issue by voanhduy1512** [nrdxp/cfdyndns#8]
Hi,

Thanks for releasing new version tag to help me with https://github.com/NixOS/nixpkgs/pull/75865. But in v0.0.2, the version in Cargo.toml is updated but not in Cargo.lock, could you bump the version again.

Thank you very much

**Comment by voanhduy1512** [comment]
Hi, just a friendly ping @colemickens

**Comment by colemickens** [comment]
@voanhduy1512 I don't even remember this, but I have local changes that I can't explain or remember. I'm looking at this now, so sorry to have left this in an unusable state, that's very frustrating.

**Comment by colemickens** [comment]
This should be fixed now. Can you confirm?

**Comment by voanhduy1512** [comment]
Now the problem is you may need to bump version again because git tag v0.0.2 is not contained the fix.

**Comment by bhipple** [comment]
Any chance we could get a v0.0.3 with the fixed Cargo.lock?

**Comment by nrdxp** [comment]
fixed in latest release
